config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#top'
  get '/signup', to: 'users#new'

  # ログイン機能
  get    '/login', to: 'sessions#new'
  post   '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :users do
    member do
      get 'edit_basic_info'                 # 基本情報編集
      patch 'update_basic_info'             # 基本情報編集更新
      get 'attendances/edit_one_month'      # 勤怠編集
      patch 'attendances/update_one_month'  # 勤怠編集更新
    end
    resources :attendances, only: :update
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :attendances, dependent: :destroy
  # 「remember_token」という仮想の属性を作成します。
  attr_accessor :remember_token               # user.remember_tokenメソッドを使える
  
  before_save { self.email = email.downcase }  # 現在のメールアドレス（self.email）の値をdowncaseメソッドを使って小文字に変換
  
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i      # 正規表現でメールアドレスのフォーマットを検証できる
  validates :email, presence: true, length: { maximum: 100 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: true                            # 一意性の検証 他に同じデータがない
  validates :department, length: { in: 2..30 }, allow_blank: true   # 値が空文字""の場合バリデーションをスルー
  validates :basic_time, presence: true
  validates :work_time, presence: true
  has_secure_password                        # パスワードハッシュ化
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true  #編集時 パスワードはスルーして更新
 
  
  # 渡された文字列のハッシュ値を返します。
  def User.digest(string)
    cost = 
      if ActiveModel::SecurePassword.min_cost
        BCrypt::Engine::MIN_COST
      else
        BCrypt::Engine.cost
      end
    BCrypt::Password.create(string, cost: cost)
  end


  # ランダムなトークンを返します。
  def User.new_token
    SecureRandom.urlsafe_base64
  end                            # ランダムに生成したトークンをハッシュ化（ダイジェストとして保存するため）する準備は整いました
  
  
  # 永続セッションのためハッシュ化したトークンをデータベースに記憶します。
  def remember
    self.remember_token = User.new_token       # ハッシュ化されたトークン情報」を代入
    update_attribute(:remember_digest, User.digest(remember_token))  # トークンダイジェストを更新
  end
  
  
  # トークンがダイジェストと一致すればtrueを返します。
  # cookiesに保存されているremember_tokenがDBにあるremember_digestと一致することを確認 トークン認証
  def authenticated?(remember_token)
  # ダイジェストが存在しない場合はfalseを返して終了します。
  return false if remember_digest.nil?
  BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  
  # ユーザーのログイン情報を破棄します。 永続的セッションを終了
  def forget
    update_attribute(:remember_digest, nil)
  end
  
  
  def self.search(search)  # メソッドはコントローラから呼び出すもの
      if search
        where(['name LIKE ?', "%#{search}%"])  # 文字列を検索 Userテーブルのカラム(name)から(LIKE)、検索ワード(search)にかする文字列はないか見ている
      else
        all  # 検索ワードが無い場合に、Userテーブルから全てのレコードを返す
      end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]        # @userをセットする
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :edit_basic_info, :update_basic_info]   # ログインを要求
  before_action :correct_user, only: [:edit, :update]            # 正しいユーザーであることを要求 ユーザー自身のみが情報を編集・更新できる
  before_action :admin_user, only: [:destroy, :edit_basic_info, :update_basic_info]       # 管理者のみ削除
  before_action :set_one_month, only: :show  # # ページ出力前に1ヶ月分のデータの存在を確認・セットします。1ヶ月分のデータが無い状態を防ぐ
  before_action :admin_or_correct_user, only: :show


  def index
    @users = User.paginate(page: params[:page])  # ページネーション
    if params[:search].present?
      @users = @users.search(params[:search])
    end 
  end

  def show 
   @worked_sum = @attendances.where.not(started_at: nil).count  # 出勤日数を表示
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = '新規作成に成功しました。'
      redirect_to @user
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:success] = "ユーザー情報を更新しました。"
      redirect_to @user
    else
      render :edit      
    end
  end

  def destroy
    @user.destroy
    flash[:success] = "#{@user.name}のデータを削除しました。"
    redirect_to users_url
  end

  def edit_basic_info
  end


  def update_basic_info
    if @user.update_attributes(basic_info_params)
      flash[:success] = "#{@user.name}の基本情報を更新しました。"
    else
      flash[:danger] = "#{@user.name}の更新は失敗しました。<br>" + @user.errors.full_messages.join("<br>")
    end
    redirect_to users_url
  end
  
  
end

app/helpers/users_helper.rb
module UsersHelper

  # 勤怠基本情報を指定のフォーマットで返します。  
  def format_basic_info(time)
    format("%.2f", ((time.hour * 60) + time.min) / 60.0)
  end
end

app/views/users/_form.html.erb
<!-- フォーム部分をパーシャル化 -->
<!-- @userが新規のユーザーオブジェクトか、それともすでにデータベースに存在する既存のオブジェクトかをRailsが判定 -->
<!-- 新規オブジェクトならPOSTリクエスト、既存オブジェクトならPATCHリクエストが送信 -->

<%= form_with(model: @user, local: true) do |f| %>
  <%= render 'shared/error_messages', object: @user %>

  <%= f.label :name, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :name, class: "form-control" %>

  <%= f.label :email, class: "label-#{yield(:class_text)}" %>
  <%= f.email_field :email, class: "form-control" %>

  <%= f.label :department, class: "label-#{yield(:class_text)}" %>
  <%= f.text_field :department, class: "form-control" %>

  <%= f.label :password, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password, class: "form-control" %>

  <%= f.label :password_confirmation, class: "label-#{yield(:class_text)}" %>
  <%= f.password_field :password_confirmation, class: "form-control" %>

  <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<% provide(:class_text, 'user--edit') %>
<% provide(:button_text, '更新') %>
<h1>ユーザー情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit_basic_info.html.erb
<% provide(:class_text, 'basic-info') %>
<% provide(:button_text, '更新') %>

<div class="ccontainer">
   <h1>基本情報編集</h1> 
       
      <div class="row">
        <div class="col-md-4 col-md-offset-4">
          <%= form_with(model: @user, url: update_basic_info_user_path(@user), local: true, method: :patch) do |f| %>
            <%= render 'shared/error_messages', object: @user %>


            <%= f.label :work_time, "指定勤務時間", class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :work_time, class: "form-control" %>
            
             <%= f.label :basic_time, "基本時間", class: "label-#{yield(:class_text)}" %>
            <%= f.time_field :basic_time, class: "form-control" %>

            
            <%= f.submit yield(:button_text), class: "btn btn-primary btn-block btn-#{yield(:class_text)}" %>
          <% end %>
        </div>
 　　　　 </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All Users') %>
<% if params[:search].present? %>
  <h1>検索結果</h1>
<% else %>
  <h1>ユーザー一覧</h1>
<% end %>

  <p class="search-head col-md-offset-8">ユーザー名検索</p>
  <form class="col-md-offset-8">
    <%= form_tag(users_path, :method => "get") do %>  
        <%= text_field_tag :search, params[:search] %>  <!-- params[:search])で検索フォームに入力したものを受け取ります -->
        <%= submit_tag "検索", :name => nil, class: "btn btn-sm btn-primary seach-btn" %>
    <% end %>
  </form>
    
      
  <%= will_paginate %>
  <table class="table table-condensed table-hover" id="table-users">
    <thead>
      <tr>
        <th><%= User.human_attribute_name :name %></th>
        <th class="center"><%= User.human_attribute_name :department %></th>
        <% if current_user.admin? %>
          <th class="center"><%= User.human_attribute_name :basic_time %></th>
          <th class="center"><%= User.human_attribute_name :work_time %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>

    <% @users.each do |user| %>
      <tr>
        <td>
          <% if current_user.admin? %>
            <%= link_to user.name, user %>
          <% else %>
            <%= user.name %>
          <% end %>
        </td>
        <td class="center"><%= user.department.present? ? user.department : "未所属" %></td>
        <% if current_user.admin? %>
          <td class="center"><%= format_basic_info(user.basic_time) %></td>
          <td class="center"><%= format_basic_info(user.work_time) %></td>
        <% end %>
        <td class="center">
          <% if current_user.admin? && !current_user?(user) %>
            <%= link_to "基本情報編集", edit_basic_info_user_path(user), class: "btn btn-success" %>
            <%= link_to "削除", user, method: :delete,
                data: { confirm: "削除してよろしいですか？" }, class: "btn btn-danger" %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </table>
  <%= will_paginate %>
</div>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<% provide(:class_text, 'signup') %>
<% provide(:button_text, '新規作成') %>
<h1>アカウント作成</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render 'form' %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div>
  <table class="table table-bordered table-condensed user-table">
    <tr>
      <td>
        <%= link_to "←", user_path(date: @first_day.prev_month), class: "btn btn-outline-dark" %>
        <%= l(@first_day, format: :middle) %>
        時間管理表
        <%= link_to "→", user_path(date: @first_day.next_month), class: "btn btn-outline-dark" %>
        </td>
      <td>指定勤務時間 <%= format_basic_info(@user.work_time) %></td>
      <td colspan="3"><%= format_basic_info(@user.basic_time) %> 基本時間</td>
      <td>初日 <%= l(@first_day, format: :short) %></td>
    </tr>

    <tr>
      <td>所属：<%= @user.department.present? ? @user.department : "未所属" %></td>
      <td>名前：<%= @user.name %></td>
      <td>コード</td>
      <td></td>
      <td>出勤日数：<%= @worked_sum %>日</td>
      <td>締め <%= l(@last_day, format: :short) %></td>
    </tr>
  </table>
</div>

<div class="btn-users-show">
  <%= link_to "勤怠を編集", attendances_edit_one_month_user_path(date: @first_day), class: "btn btn-primary" %>
</div>

<div>
  <table class="table table-bordered table-condensed table-hover" id="table-attendances">
    <thead>
      <tr>
        <th rowspan="2">日付</th>
        <th rowspan="2">曜日</th>
        <th colspan="3">出社</th>
        <th colspan="3">退社</th>
        <th rowspan="2">在社時間</th>
        <th rowspan="2">備考</th>
      </tr>
      <tr>
        <th>時</th>
        <th>分</th>
        <th></th>
        <th>時</th>
        <th>分</th>
        <th></th>
      </tr>
    </thead>

    <tbody>
      <% @attendances.each do |day| %>
        <% 
          css_class = 
          case %w{日 月 火 水 木 金 土}[day.worked_on.wday]
          when '土'
            'text-prima ry'
          when '日'
            'text-danger'
          end
        %>
        <tr>
          <td><%= l(day.worked_on, format: :short) %></td>
          <td class="<%= css_class %>"><%= $days_of_the_week[day.worked_on.wday] %></td>
          <td><%= format_hour(day.started_at) if day.started_at.present? %></td>
          <td><%= format_min(day.started_at) if day.started_at.present? %></td>
          <td>
            <% if btn_text = attendance_state(day) %>
              <%= link_to "#{btn_text}登録", user_attendance_path(@user, day), method: :patch, class: "btn btn-primary btn-attendance" %>
            <% end %>
          </td>
          <td><%= format_hour(day.finished_at) if day.finished_at.present? %></td>
          <td><%= format_min(day.finished_at) if day.finished_at.present? %></td>
          <td></td>
          <td>
            <% if day.started_at.present? && day.finished_at.present? %>
             <%= str_times = working_times(day.started_at, day.finished_at) %>
             <% @total_working_times = @total_working_times.to_f + str_times.to_f %>
            <% end %>
          </td>
          <td><%= day.note %></td>
        </tr>
      <% end %>
    <tr>
      <td colspan="2"><%= format_basic_info(@user.work_time).to_f * @worked_sum %></td> <!-- to_fメソッドにより変換した値を足している -->
      <td colspan="6"></td>
      <td><%= format("%.2f", @total_working_times.to_f) %></td>
      <td></td>
    </tr>
    </tbody>
  </table>
</div>